# Generated by Django 3.2.3 on 2021-07-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(null=True),
        ),
    ]
